[build]
rustflags = ["-g"]

[env]
RUST_BACKTRACE = "full"

[profile.release]
debug = true

[alias]
test-dev = "test --no-default-features --release -- --nocapture --test-threads=1"
br = "build --release --no-default-features"