name: atlas-zero
channels:
  - defaults
dependencies:
  - pip:
      - atlas-chess==0.0.10
      - matplotlib==3.9.2
      - ml-dtypes==0.5.0
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - pytest==8.3.3
      - scipy==1.15.1
      - sympy==1.13.2
      - torch==2.4.1
      - tqdm==4.66.5