name: Version Bump

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Bump version
      run: |
        cargo install cargo-bump
        cargo bump patch

    - name: Commit and push changes
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Cargo.toml Cargo.lock
        git commit -m "Bump version"
        git push origin HEAD:$BRANCH_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
